const API_KEY = process.env.NEXT_PUBLIC_AZURE_AI_TRANSLATOR_API_KEY;
const API_LOCATION = process.env.NEXT_PUBLIC_AZURE_AI_TRANSLATOR_API_LOCATION;
const API_ENDPOINT = process.env.NEXT_PUBLIC_AZURE_AI_TRANSLATOR_ENDPOINT;

export { API_KEY, API_LOCATION, API_ENDPOINT };
