// AI Language translator
export const AZURE_AI_TRANSLATOR_API_KEY =
  process.env.NEXT_PUBLIC_AZURE_AI_TRANSLATOR_API_KEY;
export const AZURE_AI_TRANSLATOR_API_ENDPOINT =
  process.env.NEXT_PUBLIC_AZURE_AI_TRANSLATOR_ENDPOINT;

export const AZURE_TEXT_TO_SPEECH_API_KEY =
  process.env.NEXT_PUBLIC_AZURE_TEXT_TO_SPEECH_API_KEY;

export const AZURE_RESOURCES_API_REGION =
  process.env.NEXT_PUBLIC_AZURE_RESOURCES_API_REGION;

export const AZURE_TEXT_TO_SPEECH_API_SYNTHESIS_VOICE_NAME =
  "en-US-JennyMultilingualNeural";
